baseURL: 'https://blog.minoru.dev/'
languageCode: ja
DefaultContentLanguage: jp
title: ã©ã‚‰ã®å¼•ãå‡ºã—
enableEmoji: true
enableGitInfo: true
hasCJKLanguage: true
googleAnalytics: UA-140449562-2
theme: PaperMod

permalinks:
  post: '/:year/:filename'

taxonomies:
  tag: tags
  archive: archives

params:
  site_description: ä¸€æ­©ä¸€æ­©ã€ã‚†ã£ãã‚Šã¨ã€‚
  ShowToc: true
  ShowShareButtons: true

  homeInfoParams:
    Title: Hi there ğŸ‘‹
    Content: 'ä¸€æ­©ä¸€æ­©ã€ã‚†ã£ãã‚Šã¨ã€‚'

  socialIcons:
    - name: twitter
      url: 'https://twitter.com/d0ra1998'
    - name: github
      url: 'https://github.com/dora1998'

markup:
  goldmark:
    renderer:
      unsafe: true
